<a href="https://colab.research.google.com/github/yelenana/machine_learning/blob/main/Rybchynska_Olena_%22HW7_Numpy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [3]:
import numpy as np

In [ ]:
arr_from_list = np.array([5, 15, 25, 35, 45])
print(arr_from_list.shape)

(5,)


In [ ]:
arr_with_zeros = np.zeros(7)
print(arr_with_zeros.shape)
print(arr_with_zeros)

(7,)
[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr_with_ones = np.ones(6)
print(arr_with_ones.shape)
print(arr_with_ones)

(6,)
[1. 1. 1. 1. 1. 1.]


In [ ]:
arr_with_range = np.arange(10, 20)
print(arr_with_range.shape)
print(arr_with_range)

(10,)
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [4]:
matrix = np.array([12, 24, 36, 48, 60])

In [ ]:
matrix_mul_2 = matrix * 2
print(matrix_mul_2)

[ 24  48  72  96 120]


In [ ]:
matrix_add_ten = matrix+10
print(matrix_add_ten)

[22 34 46 58 70]


In [ ]:
matrix_pow_two = matrix**2
print(matrix_pow_two)

[ 144  576 1296 2304 3600]


In [ ]:
matrix_sqr = matrix**0.5
print(matrix_sqr)

[3.46410162 4.89897949 6.         6.92820323 7.74596669]


OR

In [ ]:
matrix_sqr = np.sqrt(matrix)
print(matrix_sqr)

[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [7]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(f"Середнє значення - {np.mean(data)}")
print(f"Мінімум - {np.min(data)}")
print(f"Максимум - {np.max(data)}")
print(f"Сума всіх елементів - {np.sum(data)}")

Середнє значення - 45.42857142857143
Мінімум - 18
Максимум - 79
Сума всіх елементів - 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [10]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[arr>40])

15
67
[22 35 44]
[44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [13]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [14]:
display(matrix.shape)
display(matrix[0])
display(matrix[:, 1])
display(np.sum(matrix))
display(np.mean(matrix))

(3, 3)

array([2, 4, 6])

array([ 4, 10, 16])

np.int64(90)

np.float64(10.0)