<a href="https://colab.research.google.com/github/yelenana/machine_learning/blob/main/Rybchynska_Olena_%22HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.




---
### **Виконання:**



Завдання 1

In [20]:
import numpy as np


In [38]:
vector = np.random.rand(10)
vector

array([0.77806652, 0.63247116, 0.63646965, 0.27736061, 0.73462265,
       0.8160928 , 0.74696941, 0.71078045, 0.68333434, 0.67851249])

In [42]:
vector.shape

(10,)

In [39]:
vector2 = np.array([np.random.uniform(0, 1) for i in range(10)])
vector2

array([0.06053548, 0.8468627 , 0.44104186, 0.18815414, 0.09375964,
       0.84422753, 0.94089918, 0.9120508 , 0.68591873, 0.74431083])

Завдання 2

In [23]:
matrix_a = np.array([[11,14,17],[20,23,26],[29,32,35]])
matrix_a

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [24]:
matrix_a.shape

(3, 3)



---




### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.




---



1. Додавання значення до вектора і округлення

In [29]:
vector_rand_10 = np.round(vector_rand + 10, 2)
vector_rand_10

array([10.32, 10.86, 10.27, 10.83, 10.81, 10.74, 10.61, 10.64, 10.37,
       10.21])

2. Множення на 10

In [30]:
matrix_a = matrix_a * 2
matrix_a

array([[ 44,  56,  68],
       [ 80,  92, 104],
       [116, 128, 140]])

3. Створення вектора

In [31]:
vector_sqrt = vector_rand ** 2
vector_sqrt

array([0.10515586, 0.73798614, 0.07224602, 0.68406471, 0.6493809 ,
       0.54351639, 0.37247603, 0.40449321, 0.13729829, 0.04374469])



---




### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [28]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])



---



1. Щоб отримати матрицю розмірністю (2, 2), треба множити B на A (тому що 2x3 * 3x2 = 2x2).

In [33]:
result_matrix=np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

2.

In [34]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

3.

In [35]:
np.dot(result_matrix,D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])



---




### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.






---



In [36]:
# 1. Транспонування result_matrix
transposed_result_matrix = result_matrix.T
transposed_result_matrix

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [40]:
# 2. Транспонування вектора
transposed_vector = vector.T
transposed_vector

array([0.77806652, 0.63247116, 0.63646965, 0.27736061, 0.73462265,
       0.8160928 , 0.74696941, 0.71078045, 0.68333434, 0.67851249])

In [43]:
transposed_vector.shape

(10,)

зміни розміру не бачу

In [44]:
# 3. Використання numpy.expand_dims
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.77806652],
       [0.63247116],
       [0.63646965],
       [0.27736061],
       [0.73462265],
       [0.8160928 ],
       [0.74696941],
       [0.71078045],
       [0.68333434],
       [0.67851249]])

In [45]:
# Транспонування column_vector
transposed_column_vector = column_vector.T
transposed_column_vector.shape

(1, 10)

In [46]:
transposed_column_vector

array([[0.77806652, 0.63247116, 0.63646965, 0.27736061, 0.73462265,
        0.8160928 , 0.74696941, 0.71078045, 0.68333434, 0.67851249]])